# Generated by Django 3.2.9 on 2021-12-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazonPriceTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='prices',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.FloatField(default=-1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=70)),
                ('products', models.ManyToManyField(to='AmazonPriceTracker.Products')),
            ],
        ),
    ]
